### ISSUE TITLE
[RFC] Version 5.2 and 5.3 broken

### ISSUE THREAD

**Issue by veloxy** [yappabe/docker-apache-php#4]
Both version 5.2 and 5.3 builds are broken, even the successful 5.3 build from 10 months ago gives nothing but segfaults. We should either remove them or fix them, what do you think?

**Comment by b-franco** [comment]
I'd say remove, because they're both EOL. But we do have some old projects running on 5.3, don't we? Has 5.2 even ever been used?

**Comment by veloxy** [comment]
Well I've just tried putting a project on 5.3 (previously on 5.4) to match the production environment,  I was not able to get it working as it kept throwing segmentation faults.

```
[notice] child pid 14 exit signal Segmentation fault (11)
```

**Comment by veloxy** [comment]
@StijnRuts was having similar issues with another project that was on 5.3. We really should just migrate those projects at least to 5.4, ideally to 5.6. I'll pick it up in the dev meeting.
